spring:
  application:
    name: MyZone
  
  # --- 1. Configuração do MySQL (JPA) ---
  datasource:
    url: jdbc:mysql://localhost:3306/myzone_db?createDatabaseIfNotExist=true
    username: myzone_app_user 
    password: QWERqwer132     
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update 
    show-sql: true
    
  # --- 2. Configuração do MongoDB ---
  data:
    mongodb:
      uri: mongodb://localhost:27017/myzone_mongo_db

# --- 3. Chaves de API ---
tmdb:
  api:
    key: "8540f532b05e225bb1803f9941d43982" # (A tua chave TMDb)

google:
  books:
    api:
      key: "AIzaSyD0CfHYT5r4mVlR_8C28nSbUuk4uv4vDRc" # (A tua chave Google Books)